name: Update Citations Histogram

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday

jobs:
  update-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests matplotlib pandas

      - name: Fetch Citation Data and Generate Histogram
        run: python fetch_citations.py

      - name: Commit and push if changes
        run: |
          git config --global user.email "enddl22@gmail.com"
          git config --global user.name "inkyusa"
          git add citation_histogram.png
          git commit -m "Update citation histogram" -a || echo "No changes to commit"
          git push